-- 활성 회원 기본 현황 (단순 버전)
-- 복잡한 JOIN 없이 USERS 테이블만 활용

SELECT 
  COUNT(*) as TOTAL_ACTIVE_MEMBERS,
  COUNT(CASE WHEN U_KIND = 'DOC001' THEN 1 END) as DOCTOR_COUNT,
  COUNT(CASE WHEN U_KIND = 'PHM001' THEN 1 END) as PHARMACIST_COUNT,
  COUNT(CASE WHEN U_KIND = 'NUR001' THEN 1 END) as NURSE_COUNT,
  ROUND(COUNT(CASE WHEN U_KIND = 'DOC001' THEN 1 END) * 100.0 / COUNT(*), 1) as DOCTOR_RATE
FROM USERS u
WHERE u.U_ALIVE = 'Y'
  AND u.U_REG_DATE >= DATE_SUB(NOW(), INTERVAL 12 MONTH);