-- 프로필-행동 조인 및 분포 비교 쿼리

WITH active_segment AS (
  -- HEAVY 세그먼트 회원 식별
  SELECT DISTINCT u.U_ID
  FROM USERS u
  WHERE u.U_KIND = 'DOC001' AND u.U_ALIVE = 'Y'
    AND EXISTS (
      SELECT 1 FROM USER_LOGIN ul 
      WHERE ul.U_ID = u.U_ID 
      AND ul.LOGIN_DATE >= DATE_SUB(NOW(), INTERVAL 3 MONTH)
      GROUP BY ul.U_ID HAVING COUNT(*) >= 10
    )
),
all_doctors AS (
  -- 전체 의사 회원
  SELECT u.U_ID, ud.MAJOR_CODE, ud.WORK_TYPE_CODE
  FROM USERS u
  INNER JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID  
  WHERE u.U_KIND = 'DOC001' AND u.U_ALIVE = 'Y'
),
major_distribution AS (
  -- 전문과목별 분포 계산
  SELECT 
    cm.CODE as MAJOR_CODE,
    cm.CODE_NAME as MAJOR_NAME,
    COUNT(CASE WHEN a.U_ID IS NOT NULL THEN 1 END) as ACTIVE_COUNT,
    COUNT(ad.U_ID) as TOTAL_COUNT,
    ROUND(COUNT(CASE WHEN a.U_ID IS NOT NULL THEN 1 END) * 100.0 / COUNT(ad.U_ID), 2) as ACTIVE_RATE,
    ROUND(COUNT(ad.U_ID) * 100.0 / (SELECT COUNT(*) FROM all_doctors), 2) as TOTAL_RATE
  FROM CODE_MASTER cm
  LEFT JOIN all_doctors ad ON cm.CODE = ad.MAJOR_CODE
  LEFT JOIN active_segment a ON ad.U_ID = a.U_ID
  WHERE cm.CODE_TYPE = 'MAJOR' 
    AND cm.USE_YN = 'Y'
  GROUP BY cm.CODE, cm.CODE_NAME
  HAVING COUNT(ad.U_ID) > 0
),
work_type_distribution AS (
  -- 근무형태별 분포 계산  
  SELECT 
    cm.CODE as WORK_TYPE_CODE,
    cm.CODE_NAME as WORK_TYPE_NAME,
    COUNT(CASE WHEN a.U_ID IS NOT NULL THEN 1 END) as ACTIVE_COUNT,
    COUNT(ad.U_ID) as TOTAL_COUNT,
    ROUND(COUNT(CASE WHEN a.U_ID IS NOT NULL THEN 1 END) * 100.0 / COUNT(ad.U_ID), 2) as ACTIVE_RATE,
    ROUND(COUNT(ad.U_ID) * 100.0 / (SELECT COUNT(*) FROM all_doctors), 2) as TOTAL_RATE
  FROM CODE_MASTER cm
  LEFT JOIN all_doctors ad ON cm.CODE = ad.WORK_TYPE_CODE
  LEFT JOIN active_segment a ON ad.U_ID = a.U_ID  
  WHERE cm.CODE_TYPE = 'WORK_TYPE'
    AND cm.USE_YN = 'Y'
  GROUP BY cm.CODE, cm.CODE_NAME
  HAVING COUNT(ad.U_ID) > 0
)
-- 최종 결과: 유의미한 차이(+5%p 이상)를 보이는 세그먼트
SELECT 
  'MAJOR' as CATEGORY_TYPE,
  MAJOR_CODE as CATEGORY_CODE, 
  MAJOR_NAME as CATEGORY_NAME,
  ACTIVE_COUNT,
  TOTAL_COUNT,
  ACTIVE_RATE,
  TOTAL_RATE,
  (ACTIVE_RATE - TOTAL_RATE) as DIFFERENCE_POINT,
  CASE WHEN (ACTIVE_RATE - TOTAL_RATE) >= 5.0 THEN 'Y' ELSE 'N' END as IS_SIGNIFICANT
FROM major_distribution
WHERE (ACTIVE_RATE - TOTAL_RATE) >= 5.0

UNION ALL

SELECT 
  'WORK_TYPE' as CATEGORY_TYPE,
  WORK_TYPE_CODE as CATEGORY_CODE,
  WORK_TYPE_NAME as CATEGORY_NAME, 
  ACTIVE_COUNT,
  TOTAL_COUNT,
  ACTIVE_RATE,
  TOTAL_RATE,
  (ACTIVE_RATE - TOTAL_RATE) as DIFFERENCE_POINT,
  CASE WHEN (ACTIVE_RATE - TOTAL_RATE) >= 5.0 THEN 'Y' ELSE 'N' END as IS_SIGNIFICANT
FROM work_type_distribution
WHERE (ACTIVE_RATE - TOTAL_RATE) >= 5.0

ORDER BY DIFFERENCE_POINT DESC;