-- 월별 가입자 추이 분석 (최근 24개월)
-- USERS 테이블의 실제 컬럼만 사용

SELECT 
  DATE_FORMAT(u.U_REG_DATE, '%Y-%m') as REG_MONTH,
  COUNT(*) as NEW_MEMBERS
FROM USERS u
WHERE u.U_REG_DATE >= DATE_SUB(NOW(), INTERVAL 24 MONTH)
  AND u.U_ALIVE = 'Y'
GROUP BY DATE_FORMAT(u.U_REG_DATE, '%Y-%m')
ORDER BY REG_MONTH DESC
LIMIT 24;