// PodcastScript.tsx - 메인 컴포넌트
import { ScriptHeader } from './components/ScriptHeader';
import { SectionBlock } from './components/SectionBlock';
import { PODCAST_SCRIPT, ANALYSIS_DATA } from './data';

export function PodcastScript() {
  const script = PODCAST_SCRIPT;
  const analysis = ANALYSIS_DATA;

  return (
    <div className="min-h-screen bg-gray-100 py-8">
      <div className="max-w-4xl mx-auto px-4">
        <ScriptHeader
          episodeId={script.episodeId}
          createdAt={script.createdAt}
          totalDuration={script.totalDuration}
        />

        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-lg font-bold text-gray-800 mb-4">📋 대본</h2>
          <div className="text-sm text-gray-600 mb-4">
            총 {script.wordCount}단어 | {script.sections.length}개 섹션
          </div>

          {script.sections.map((section) => (
            <SectionBlock key={section.id} section={section} />
          ))}
        </div>

        <div className="bg-white rounded-lg shadow-md p-6">
          <h2 className="text-lg font-bold text-gray-800 mb-4">📊 분석 결과 요약</h2>

          <div className="mb-4">
            <h3 className="font-semibold text-gray-700 mb-2">트렌드 키워드</h3>
            <div className="flex flex-wrap gap-2">
              {analysis.trendKeywords.map((keyword) => (
                <span
                  key={keyword}
                  className="px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm"
                >
                  #{keyword}
                </span>
              ))}
            </div>
          </div>

          <div>
            <h3 className="font-semibold text-gray-700 mb-2">TOP 5 게시물</h3>
            <div className="space-y-2">
              {analysis.posts.map((post, index) => (
                <div
                  key={post.boardIdx}
                  className="flex items-center gap-3 p-2 bg-gray-50 rounded"
                >
                  <span className="w-6 h-6 flex items-center justify-center bg-gray-800 text-white text-xs font-bold rounded">
                    {index + 1}
                  </span>
                  <span className="flex-1 text-sm text-gray-700">{post.title}</span>
                  <span className="text-xs text-gray-500">
                    👍 {post.agreeCnt} · 💬 {post.commentCount}
                  </span>
                  <span
                    className={`px-2 py-0.5 text-xs rounded ${
                      post.suitability === 'high'
                        ? 'bg-green-100 text-green-800'
                        : post.suitability === 'medium'
                        ? 'bg-yellow-100 text-yellow-800'
                        : 'bg-red-100 text-red-800'
                    }`}
                  >
                    {post.suitability === 'high' ? '적합' : post.suitability === 'medium' ? '보통' : '낮음'}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="text-center mt-6 text-sm text-gray-500">
          Generated by Query Skill v3.2 | {analysis.generatedAt}
        </div>
      </div>
    </div>
  );
}
