-- ============================================
-- case_04_근무형태별분포비교
-- 근무형태별 분포 - 활성 회원 vs 전체 회원 비교
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT cm.CODE_NAME as work_type, COUNT(CASE WHEN u.U_ALIVE = 'UST001' THEN 1 END) as active_count, COUNT(*) as total_count, ROUND(COUNT(CASE WHEN u.U_ALIVE = 'UST001' THEN 1 END) * 100.0 / COUNT(*), 2) as active_ratio FROM USERS u LEFT JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID LEFT JOIN CODE_MASTER cm ON cm.KBN = 'WTP' AND cm.CODE = ud.U_WORK_TYPE_1 WHERE u.U_KIND = 'UKD001' AND ud.U_WORK_TYPE_1 IS NOT NULL GROUP BY ud.U_WORK_TYPE_1, cm.CODE_NAME ORDER BY active_count DESC
