-- ============================================
-- case_4_전문과목별_분포_전체회원
-- 전체 의사 회원의 전문과목별 분포 (활성 회원과 비교용)
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT cm.CODE_NAME as specialty, COUNT(*) as total_count, SUM(CASE WHEN u.U_ALIVE = 'UST001' THEN 1 ELSE 0 END) as active_count, ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM USERS WHERE U_KIND = 'UKD001'), 2) as total_percentage, ROUND(SUM(CASE WHEN u.U_ALIVE = 'UST001' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as active_ratio FROM USERS u JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID JOIN CODE_MASTER cm ON cm.KBN = 'SPC' AND cm.CODE = ud.U_MAJOR_CODE_1 WHERE u.U_KIND = 'UKD001' AND ud.U_MAJOR_CODE_1 IS NOT NULL GROUP BY ud.U_MAJOR_CODE_1, cm.CODE_NAME HAVING total_count >= 100 ORDER BY active_count DESC LIMIT 20
