-- ============================================
-- case_03_근무형태별_활성도_비교
-- 개원의 vs 봉직의 활성도 및 휴면 위험도 비교
-- Generated by AnalysisAgent
-- Date: 2025-12-18
-- ============================================

SELECT 
    wt.CODE_NAME as work_type,
    COUNT(*) as total_users,
    SUM(CASE WHEN DATEDIFF(CURDATE(), STR_TO_DATE(last_login.last_date, '%Y%m%d')) <= 7 THEN 1 ELSE 0 END) as active_users,
    SUM(CASE WHEN DATEDIFF(CURDATE(), STR_TO_DATE(last_login.last_date, '%Y%m%d')) BETWEEN 8 AND 30 THEN 1 ELSE 0 END) as risk_users,
    ROUND(AVG(DATEDIFF(CURDATE(), STR_TO_DATE(last_login.last_date, '%Y%m%d'))), 1) as avg_inactive_days
FROM USERS u
INNER JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID
INNER JOIN CODE_MASTER wt ON wt.KBN = 'WTP' AND wt.CODE = ud.U_WORK_TYPE_1
INNER JOIN (
    SELECT U_ID, MAX(LOGIN_DATE) as last_date
    FROM USER_LOGIN 
    WHERE LOGIN_DATE >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 90 DAY), '%Y%m%d')
    GROUP BY U_ID
) last_login ON u.U_ID = last_login.U_ID
WHERE u.U_KIND = 'UKD001' 
    AND u.U_ALIVE = 'UST001'
    AND ud.U_WORK_TYPE_1 IN ('WTP006', 'WTP007')
GROUP BY ud.U_WORK_TYPE_1, wt.CODE_NAME
LIMIT 100
