-- ============================================
-- case_06_AI에이전트타겟후보제안
-- AI Agent Use Case 우선 적용 대상 - 활성도 높은 세그먼트 식별
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT 'HIGH_PRIORITY' as segment_type, cm1.CODE_NAME as specialty, cm2.CODE_NAME as work_type, COUNT(*) as target_count, ROUND(AVG(DATEDIFF(CURDATE(), STR_TO_DATE(u.U_REG_DATE, '%Y%m%d'))/365), 1) as avg_career_years FROM USERS u JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID LEFT JOIN CODE_MASTER cm1 ON cm1.KBN = 'SPC' AND cm1.CODE = ud.U_MAJOR_CODE_1 LEFT JOIN CODE_MASTER cm2 ON cm2.KBN = 'WTP' AND cm2.CODE = ud.U_WORK_TYPE_1 WHERE u.U_ALIVE = 'UST001' AND u.U_KIND = 'UKD001' AND ud.U_MAJOR_CODE_1 IN ('SPC103', 'SPC104', 'SPC105', 'SPC106', 'SPC107') AND ud.U_WORK_TYPE_1 IN ('WTP006', 'WTP007') GROUP BY ud.U_MAJOR_CODE_1, ud.U_WORK_TYPE_1, cm1.CODE_NAME, cm2.CODE_NAME HAVING COUNT(*) >= 100 ORDER BY target_count DESC LIMIT 10
