-- ============================================
-- case_02_의사회원_휴면위험_프로파일
-- 의사 회원의 전문과목별 휴면 위험도 분석
-- Generated by AnalysisAgent
-- Date: 2025-12-18
-- ============================================

SELECT 
    cm.CODE_NAME as major_specialty,
    CASE 
        WHEN DATEDIFF(CURDATE(), STR_TO_DATE(MAX(ul.LOGIN_DATE), '%Y%m%d')) <= 14 THEN 'LOW_RISK'
        WHEN DATEDIFF(CURDATE(), STR_TO_DATE(MAX(ul.LOGIN_DATE), '%Y%m%d')) <= 30 THEN 'MEDIUM_RISK'
        ELSE 'HIGH_RISK'
    END AS risk_level,
    COUNT(*) as doctor_count,
    AVG(DATEDIFF(CURDATE(), STR_TO_DATE(MAX(ul.LOGIN_DATE), '%Y%m%d'))) as avg_days_inactive
FROM USERS u
INNER JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID
INNER JOIN CODE_MASTER cm ON cm.KBN = 'SPC' AND cm.CODE = ud.U_MAJOR_CODE_1
INNER JOIN USER_LOGIN ul ON u.U_ID = ul.U_ID
WHERE u.U_KIND = 'UKD001' 
    AND u.U_ALIVE = 'UST001'
    AND ul.LOGIN_DATE >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 90 DAY), '%Y%m%d')
GROUP BY u.U_ID, ud.U_MAJOR_CODE_1, cm.CODE_NAME
HAVING MAX(ul.LOGIN_DATE) IS NOT NULL
LIMIT 5000
