-- ============================================
-- case_3_전문과목별_분포_활성회원
-- 활성 의사 회원의 전문과목별 분포 (상위 20개)
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT cm.CODE_NAME as specialty, COUNT(*) as count, ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM USERS WHERE U_KIND = 'UKD001' AND U_ALIVE = 'UST001'), 2) as percentage FROM USERS u JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID JOIN CODE_MASTER cm ON cm.KBN = 'SPC' AND cm.CODE = ud.U_MAJOR_CODE_1 WHERE u.U_KIND = 'UKD001' AND u.U_ALIVE = 'UST001' AND ud.U_MAJOR_CODE_1 IS NOT NULL GROUP BY ud.U_MAJOR_CODE_1, cm.CODE_NAME ORDER BY count DESC LIMIT 20
