-- ============================================
-- case_03_회원유형별전체현황
-- 회원유형별 전체 현황 (활성/비활성 포함)
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT u.U_KIND, u.U_ALIVE, COUNT(*) as count FROM USERS u GROUP BY u.U_KIND, u.U_ALIVE ORDER BY u.U_KIND, u.U_ALIVE LIMIT 10
