-- ============================================
-- case_02_프로필행동조인분석
-- 활성 회원의 프로필과 최근 로그인 행동 패턴 분석
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT u.U_ID, u.U_KIND, ud.U_MAJOR_CODE_1, ud.U_WORK_TYPE_1, ud.U_HOSPITAL_NAME, DATEDIFF(CURDATE(), STR_TO_DATE(u.U_REG_DATE, '%Y%m%d')) as days_since_reg, (SELECT MAX(LOGIN_DATE) FROM USER_LOGIN ul WHERE ul.U_ID = u.U_ID AND ul.LOGIN_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY) LIMIT 1) as last_login_30days FROM USERS u LEFT JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID WHERE u.U_ALIVE = 'UST001' AND u.U_KIND = 'UKD001' ORDER BY u.U_REG_DATE DESC LIMIT 1000
