-- ============================================
-- case_02_회원상태현황
-- 전체 회원 상태별 현황 조회
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT u.U_ALIVE, COUNT(*) as status_count FROM USERS u GROUP BY u.U_ALIVE LIMIT 10
