-- ============================================
-- case_04_의사회원현황
-- 의사 회원만 필터링하여 상태별 조회
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT u.U_ALIVE, COUNT(*) as doctor_count FROM USERS u WHERE u.U_KIND = 'UKD001' GROUP BY u.U_ALIVE LIMIT 10
