-- ============================================
-- case_01_활성회원현황
-- 회원유형별 활성 회원 수 조회
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT u.U_KIND, COUNT(*) as member_count FROM USERS u WHERE u.U_ALIVE = 'UST001' GROUP BY u.U_KIND LIMIT 10
