-- ============================================
-- case_01_활성회원조회
-- 활성 상태인 회원 목록 조회 (페이징 처리)
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT U_ID, U_KIND, U_ALIVE FROM USERS WHERE U_ALIVE = 'UST001' ORDER BY U_ID LIMIT 10
