-- ============================================
-- case_8_경력년수별_분포
-- 활성 의사 회원의 가입 후 경과년수별 분포 (AI Agent 타겟팅용)
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT CASE WHEN DATEDIFF(NOW(), u.U_REG_DATE) / 365 < 1 THEN '1년 미만' WHEN DATEDIFF(NOW(), u.U_REG_DATE) / 365 < 3 THEN '1-3년' WHEN DATEDIFF(NOW(), u.U_REG_DATE) / 365 < 5 THEN '3-5년' WHEN DATEDIFF(NOW(), u.U_REG_DATE) / 365 < 10 THEN '5-10년' ELSE '10년 이상' END as career_group, COUNT(*) as count, ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM USERS WHERE U_KIND = 'UKD001' AND U_ALIVE = 'UST001'), 2) as percentage FROM USERS u WHERE u.U_KIND = 'UKD001' AND u.U_ALIVE = 'UST001' GROUP BY CASE WHEN DATEDIFF(NOW(), u.U_REG_DATE) / 365 < 1 THEN '1년 미만' WHEN DATEDIFF(NOW(), u.U_REG_DATE) / 365 < 3 THEN '1-3년' WHEN DATEDIFF(NOW(), u.U_REG_DATE) / 365 < 5 THEN '3-5년' WHEN DATEDIFF(NOW(), u.U_REG_DATE) / 365 < 10 THEN '5-10년' ELSE '10년 이상' END ORDER BY count DESC
