-- ============================================
-- case_02_회원유형별조회
-- 회원 유형별 활성 회원 수 집계
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT U_KIND, COUNT(*) as member_count FROM USERS WHERE U_ALIVE = 'UST001' GROUP BY U_KIND ORDER BY member_count DESC
