-- ============================================
-- case_05_활성회원프로파일요약
-- 활성 회원 프로파일 요약 리포트 - 가입연도, 전문과목, 근무형태 종합
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT YEAR(STR_TO_DATE(u.U_REG_DATE, '%Y%m%d')) as reg_year, cm1.CODE_NAME as specialty, cm2.CODE_NAME as work_type, COUNT(*) as member_count, AVG(DATEDIFF(CURDATE(), STR_TO_DATE(u.U_REG_DATE, '%Y%m%d'))) as avg_career_days FROM USERS u JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID LEFT JOIN CODE_MASTER cm1 ON cm1.KBN = 'SPC' AND cm1.CODE = ud.U_MAJOR_CODE_1 LEFT JOIN CODE_MASTER cm2 ON cm2.KBN = 'WTP' AND cm2.CODE = ud.U_WORK_TYPE_1 WHERE u.U_ALIVE = 'UST001' AND u.U_KIND = 'UKD001' AND u.U_REG_DATE >= '20200101' GROUP BY YEAR(STR_TO_DATE(u.U_REG_DATE, '%Y%m%d')), ud.U_MAJOR_CODE_1, ud.U_WORK_TYPE_1, cm1.CODE_NAME, cm2.CODE_NAME HAVING COUNT(*) >= 10 ORDER BY reg_year DESC, member_count DESC LIMIT 50
