-- ============================================
-- case_03_전체회원현황
-- 회원 상태별 현황 집계
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT U_ALIVE, U_KIND, COUNT(*) as member_count FROM USERS GROUP BY U_ALIVE, U_KIND ORDER BY U_ALIVE, U_KIND
