-- ============================================
-- case_04_가입연차별_휴면패턴_분석
-- 가입 연차별 휴면 위험도 패턴 분석
-- Generated by AnalysisAgent
-- Date: 2025-12-18
-- ============================================

SELECT 
    CASE 
        WHEN YEAR(CURDATE()) - YEAR(u.U_REG_DATE) = 0 THEN '신규회원(1년미만)'
        WHEN YEAR(CURDATE()) - YEAR(u.U_REG_DATE) <= 3 THEN '초급회원(1-3년)'
        WHEN YEAR(CURDATE()) - YEAR(u.U_REG_DATE) <= 7 THEN '중급회원(4-7년)'
        ELSE '시니어회원(8년이상)'
    END AS member_seniority,
    COUNT(*) as total_members,
    AVG(CASE WHEN last_login.last_date IS NOT NULL 
        THEN DATEDIFF(CURDATE(), STR_TO_DATE(last_login.last_date, '%Y%m%d')) 
        ELSE 365 END) as avg_inactive_days,
    SUM(CASE WHEN last_login.last_date IS NULL OR 
        DATEDIFF(CURDATE(), STR_TO_DATE(last_login.last_date, '%Y%m%d')) > 30 THEN 1 ELSE 0 END) as high_risk_count
FROM USERS u
LEFT JOIN (
    SELECT U_ID, MAX(LOGIN_DATE) as last_date
    FROM USER_LOGIN 
    WHERE LOGIN_DATE >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 180 DAY), '%Y%m%d')
    GROUP BY U_ID
) last_login ON u.U_ID = last_login.U_ID
WHERE u.U_ALIVE = 'UST001'
    AND u.U_KIND = 'UKD001'
GROUP BY 
    CASE 
        WHEN YEAR(CURDATE()) - YEAR(u.U_REG_DATE) = 0 THEN '신규회원(1년미만)'
        WHEN YEAR(CURDATE()) - YEAR(u.U_REG_DATE) <= 3 THEN '초급회원(1-3년)'
        WHEN YEAR(CURDATE()) - YEAR(u.U_REG_DATE) <= 7 THEN '중급회원(4-7년)'
        ELSE '시니어회원(8년이상)'
    END
ORDER BY avg_inactive_days DESC
LIMIT 50
