-- ============================================
-- case_01_활성회원세그먼트정의
-- HEAVY 세그먼트 회원(16,037명) 활성 회원 세그먼트 정의
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT u.U_KIND, COUNT(*) as total_count, SUM(CASE WHEN u.U_ALIVE = 'UST001' THEN 1 ELSE 0 END) as active_count, ROUND(SUM(CASE WHEN u.U_ALIVE = 'UST001' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as active_ratio FROM USERS u WHERE u.U_KIND IN ('UKD001', 'UKD003') GROUP BY u.U_KIND ORDER BY active_count DESC
