-- ============================================
-- case_7_활성회원_프로파일_요약
-- 활성 의사 회원의 종합 프로파일 현황
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT '기본정보' as category, '총 활성 회원수' as metric, COUNT(*) as value FROM USERS WHERE U_KIND = 'UKD001' AND U_ALIVE = 'UST001' UNION ALL SELECT '프로파일 완성도', '전문과목 입력률', ROUND(COUNT(ud.U_MAJOR_CODE_1) * 100.0 / COUNT(*), 1) FROM USERS u LEFT JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID WHERE u.U_KIND = 'UKD001' AND u.U_ALIVE = 'UST001' UNION ALL SELECT '프로파일 완성도', '근무형태 입력률', ROUND(COUNT(ud.U_WORK_TYPE_1) * 100.0 / COUNT(*), 1) FROM USERS u LEFT JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID WHERE u.U_KIND = 'UKD001' AND u.U_ALIVE = 'UST001' UNION ALL SELECT '프로파일 완성도', '병원명 입력률', ROUND(COUNT(ud.U_HOSPITAL_NAME) * 100.0 / COUNT(*), 1) FROM USERS u LEFT JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID WHERE u.U_KIND = 'UKD001' AND u.U_ALIVE = 'UST001'
