-- ============================================
-- case_1_활성회원_세그먼트_정의
-- 활성 상태의 의사 회원 16,037명 기본 정보 조회
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT COUNT(*) as total_count, u.U_KIND, CASE WHEN u.U_ALIVE = 'UST001' THEN '활성' ELSE '비활성' END as status FROM USERS u WHERE u.U_KIND = 'UKD001' AND u.U_ALIVE = 'UST001' GROUP BY u.U_KIND, u.U_ALIVE
