-- ============================================
-- case_01_휴면위험도_기본분석
-- 최근 로그인 기준 휴면 위험도 세그먼트 분석
-- Generated by AnalysisAgent
-- Date: 2025-12-18
-- ============================================

SELECT 
    CASE 
        WHEN DATEDIFF(CURDATE(), STR_TO_DATE(MAX(ul.LOGIN_DATE), '%Y%m%d')) <= 7 THEN 'ACTIVE'
        WHEN DATEDIFF(CURDATE(), STR_TO_DATE(MAX(ul.LOGIN_DATE), '%Y%m%d')) <= 30 THEN 'D-30 위험'
        WHEN DATEDIFF(CURDATE(), STR_TO_DATE(MAX(ul.LOGIN_DATE), '%Y%m%d')) <= 90 THEN 'D-90 위험'
        ELSE '휴면 위험'
    END AS risk_segment,
    COUNT(*) as user_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) as percentage
FROM USERS u
INNER JOIN USER_LOGIN ul ON u.U_ID = ul.U_ID
WHERE u.U_ALIVE = 'UST001'
    AND ul.LOGIN_DATE >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 180 DAY), '%Y%m%d')
GROUP BY u.U_ID, u.U_KIND
HAVING MAX(ul.LOGIN_DATE) IS NOT NULL
LIMIT 10000
