-- ============================================
-- case_9_AI_Agent_우선타겟_후보
-- AI Agent Use Case 우선 적용 대상 - 개원의 + 주요 전문과목 조합
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT cm_spc.CODE_NAME as specialty, cm_wtp.CODE_NAME as work_type, COUNT(*) as target_count, ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM USERS WHERE U_KIND = 'UKD001' AND U_ALIVE = 'UST001'), 2) as market_share FROM USERS u JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID JOIN CODE_MASTER cm_spc ON cm_spc.KBN = 'SPC' AND cm_spc.CODE = ud.U_MAJOR_CODE_1 JOIN CODE_MASTER cm_wtp ON cm_wtp.KBN = 'WTP' AND cm_wtp.CODE = ud.U_WORK_TYPE_1 WHERE u.U_KIND = 'UKD001' AND u.U_ALIVE = 'UST001' AND ud.U_WORK_TYPE_1 IN ('WTP006') AND ud.U_MAJOR_CODE_1 IS NOT NULL GROUP BY ud.U_MAJOR_CODE_1, ud.U_WORK_TYPE_1, cm_spc.CODE_NAME, cm_wtp.CODE_NAME HAVING target_count >= 50 ORDER BY target_count DESC LIMIT 15
