-- ============================================
-- case_2_프로필_행동_조인분석
-- 활성 의사 회원의 프로필 정보와 가입년도 분포
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT YEAR(u.U_REG_DATE) as reg_year, COUNT(*) as count, COUNT(ud.U_MAJOR_CODE_1) as has_specialty, COUNT(ud.U_WORK_TYPE_1) as has_work_type, COUNT(ud.U_HOSPITAL_NAME) as has_hospital FROM USERS u LEFT JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID WHERE u.U_KIND = 'UKD001' AND u.U_ALIVE = 'UST001' GROUP BY YEAR(u.U_REG_DATE) ORDER BY reg_year DESC
