-- ============================================
-- case_03_전문과목별분포비교
-- 전문과목별 분포 - 활성 회원 vs 전체 회원 비교
-- Generated by AnalysisAgent
-- Date: 2025-12-19
-- ============================================

SELECT cm.CODE_NAME as specialty, COUNT(CASE WHEN u.U_ALIVE = 'UST001' THEN 1 END) as active_count, COUNT(*) as total_count, ROUND(COUNT(CASE WHEN u.U_ALIVE = 'UST001' THEN 1 END) * 100.0 / COUNT(*), 2) as active_ratio FROM USERS u LEFT JOIN USER_DETAIL ud ON u.U_ID = ud.U_ID LEFT JOIN CODE_MASTER cm ON cm.KBN = 'SPC' AND cm.CODE = ud.U_MAJOR_CODE_1 WHERE u.U_KIND = 'UKD001' AND ud.U_MAJOR_CODE_1 IS NOT NULL GROUP BY ud.U_MAJOR_CODE_1, cm.CODE_NAME HAVING COUNT(*) >= 50 ORDER BY active_count DESC LIMIT 20
